### ISSUE TITLE
TARDIS insides overlapping 

### ISSUE THREAD

**Issue by pdglobal** [eccentricdevotion/TARDIS#194] opened 2020-02-11 20:27 UTC
**Describe the bug**

Whenever a new TARDIS is created, it;s internal coordinates overlap the previous internals.

The each new console is set to the same coordinates.

See world guard config file for more detailed example of the problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install TARDIS 4.3-b1993 on paper build 102 MC 1.15.2
[OPTIONAL] I am storing my data on a mysql database server, how ever I was able to replicate the error with the default database being used.
2. Start server
3. Create any two TARDIS seeds
4. Have player 1 make a TARDIS, then have player 2 make a TARDIS
5. The coordinates for the insides of both TARDISES are now the same in worldgaurd, AND both TARDIS doors should take you to the same TARDIS inside
6. Create a 3rd player's TARDIS, and 4th and 5th on and on this will continue to happen with each new TARDIS created. (optional)

**Log files**
(worldguard file for TARDIS_TimeVortex)
> regions:
>     tardis_pdglobal:
>         min: {x: 0, y: 0, z: 2048}
>         max: {x: 1023, y: 256, z: 3071}
>         members: {}
>         flags: {exit: deny, entry: deny, lava-fire: deny, use: allow, lighter: deny,
>             lava-flow: deny, fire-spread: deny}
>         owners:
>             players: [pdglobal]
>         type: cuboid
>         priority: 0
>     tardis_frenchee1607:
>         min: {x: 0, y: 0, z: 2048}
>         max: {x: 1023, y: 256, z: 3071}
>         members: {}
>         flags: {exit: deny, entry: deny, lava-fire: deny, use: allow, lighter: deny,
>             lava-flow: deny, fire-spread: deny}
>         owners:
>             players: [frenchee1607]
>         type: cuboid
>         priority: 0
>

**Comment by eccentricdevotion** [comment] 2020-02-11 20:29
Please attach your config file

**Comment by pdglobal** [comment] 2020-02-11 20:53
> # config file
> debug: false
> storage:
>   database: mysql
>   mysql:
>     url: mysql://localhost:3306/minecraft
>     user: root
>     password: Dunkel137982461973
>     prefix: TARDIS_
> creation:
>   create_worlds: false
>   create_worlds_with_perms: false
>   default_world: true
>   default_world_name: TARDIS_TimeVortex
>   tips_limit: 400
>   border_radius: 256
>   gamemode: survival
>   keep_night: true
>   inventory_group: 0
>   add_perms: false
>   enable_legacy: true
>   custom_schematic: true
>   custom_schematic_seed: OBSIDIAN
>   use_block_stack: true
>   use_clay: WOOL
>   count: 0
>   sky_biome: true
>   area: none
> police_box:
>   default_preset: FACTORY
>   tardis_lamp: REDSTONE_LAMP
>   name_tardis: true
>   materialise: true
>   confirm_timeout: 15
>   sign_colour: WHITE
>   set_biome: true
>   rebuild_cooldown: 10000
> travel:
>   include_default_world: false
>   tp_radius: 500
>   max_distance: 29999983
>   give_key: false
>   the_end: true
>   nether: true
>   terminal:
>     redefine: false
>     nether: world
>     the_end: world
>   land_on_water: true
>   timeout: 5
>   timeout_height: 135
>   random_attempts: 30
>   exile: false
>   per_world_perms: false
>   terminal_step: 1
>   manual_flight_delay: 60
>   grace_period: 10
>   random_circuit:
>     x: 5000
>     z: 5000
>   no_destination_malfunctions: true
> preferences:
>   language: en
>   key: AIR
>   walk_in_tardis: true
>   open_door_policy: false
>   use_worldguard: true
>   respect_worldguard: build
>   respect_towny: nation
>   respect_worldborder: true
>   respect_factions: true
>   respect_grief_prevention: true
>   sfx_volume: 10
>   difficulty: easy
>   strike_lightning: true
>   freeze_cooldown: 60
>   hads_damage: 10
>   hads_distance: 10
>   malfunction: 3
>   malfunction_end: 3
>   malfunction_nether: 3
>   use_default_condensables: true
>   heal_speed: 200
>   default_key: eleventh
>   default_sonic: eleventh
>   nerf_pistons:
>     enabled: false
>     only_tardis_worlds: true
>   render_entities: false
>   spawn_random_monsters: true
>   spawn_limit: 10
>   no_coords: false
>   no_creative_condense: false
>   vortex_fall: kill
> desktop:
>   check_blocks_before_upgrade: false
>   block_change_percent: 25
> circuits:
>   damage: false
>   malfunction_damage: 50
>   uses:
>     ars: 20
>     chameleon: 25
>     input: 50
>     invisibility: 5
>     materialisation: 50
>     memory: 20
>     randomiser: 50
>     scanner: 20
>     temporal: 20
> allow:
>   mob_farming: true
>   spawn_eggs: true
>   emergency_npc: true
>   achievements: true
>   autonomous: true
>   guardians: false
>   hads: true
>   handles: true
>   invisibility: true
>   tp_switch: true
>   all_blocks: false
>   sfx: true
>   wg_flag_set: true
>   zero_room: true
>   external_gravity: false
>   power_down: true
>   power_down_on_quit: false
>   player_difficulty: true
>   3d_doors: true
>   village_travel: false
>   perception_filter: true
>   repair: true
> growth:
>   gravity_max_distance: 15
>   gravity_max_velocity: 5
>   return_room_seed: true
>   rooms_require_blocks: false
>   rooms_condenser_percent: 100
>   room_speed: 4
>   ars_limit: 1
> arch:
>   enabled: true
>   min_time: 20
>   switch_inventory: true
>   clear_inv_on_death: false
> siege:
>   enabled: true
>   breeding: 0
>   growth: 0
>   butcher: false
>   creeper: false
>   healing: false
>   texture: false
> junk:
>   enabled: true
>   return: -1
>   particles: true
> abandon:
>   enabled: false
>   reduce_count: true
> archive:
>   enabled: true
>   limit: 3
> handles:
>   prefix: Hey Handles
>   reminders:
>     enabled: true
>     schedule: 1200
> rechargers: {}
> conversions:
>   ars_materials: true
>   condenser_materials: true
>   player_prefs_materials: true
>   block_materials: true
>   custom_preset: true
>   constructs: true
>   lowercase_world_names: true
>

**Comment by pdglobal** [comment] 2020-02-11 20:54
> # config file
> debug: false
> storage:
>   database: mysql
>   mysql:
>     url: mysql://localhost:3306/minecraft
>     user: root
>     password: *********
>     prefix: TARDIS_
> creation:
>   create_worlds: false
>   create_worlds_with_perms: false
>   default_world: true
>   default_world_name: TARDIS_TimeVortex
>   tips_limit: 400
>   border_radius: 256
>   gamemode: survival
>   keep_night: true
>   inventory_group: 0
>   add_perms: false
>   enable_legacy: true
>   custom_schematic: true
>   custom_schematic_seed: OBSIDIAN
>   use_block_stack: true
>   use_clay: WOOL
>   count: 0
>   sky_biome: true
>   area: none
> police_box:
>   default_preset: FACTORY
>   tardis_lamp: REDSTONE_LAMP
>   name_tardis: true
>   materialise: true
>   confirm_timeout: 15
>   sign_colour: WHITE
>   set_biome: true
>   rebuild_cooldown: 10000
> travel:
>   include_default_world: false
>   tp_radius: 500
>   max_distance: 29999983
>   give_key: false
>   the_end: true
>   nether: true
>   terminal:
>     redefine: false
>     nether: world
>     the_end: world
>   land_on_water: true
>   timeout: 5
>   timeout_height: 135
>   random_attempts: 30
>   exile: false
>   per_world_perms: false
>   terminal_step: 1
>   manual_flight_delay: 60
>   grace_period: 10
>   random_circuit:
>     x: 5000
>     z: 5000
>   no_destination_malfunctions: true
> preferences:
>   language: en
>   key: AIR
>   walk_in_tardis: true
>   open_door_policy: false
>   use_worldguard: true
>   respect_worldguard: build
>   respect_towny: nation
>   respect_worldborder: true
>   respect_factions: true
>   respect_grief_prevention: true
>   sfx_volume: 10
>   difficulty: easy
>   strike_lightning: true
>   freeze_cooldown: 60
>   hads_damage: 10
>   hads_distance: 10
>   malfunction: 3
>   malfunction_end: 3
>   malfunction_nether: 3
>   use_default_condensables: true
>   heal_speed: 200
>   default_key: eleventh
>   default_sonic: eleventh
>   nerf_pistons:
>     enabled: false
>     only_tardis_worlds: true
>   render_entities: false
>   spawn_random_monsters: true
>   spawn_limit: 10
>   no_coords: false
>   no_creative_condense: false
>   vortex_fall: kill
> desktop:
>   check_blocks_before_upgrade: false
>   block_change_percent: 25
> circuits:
>   damage: false
>   malfunction_damage: 50
>   uses:
>     ars: 20
>     chameleon: 25
>     input: 50
>     invisibility: 5
>     materialisation: 50
>     memory: 20
>     randomiser: 50
>     scanner: 20
>     temporal: 20
> allow:
>   mob_farming: true
>   spawn_eggs: true
>   emergency_npc: true
>   achievements: true
>   autonomous: true
>   guardians: false
>   hads: true
>   handles: true
>   invisibility: true
>   tp_switch: true
>   all_blocks: false
>   sfx: true
>   wg_flag_set: true
>   zero_room: true
>   external_gravity: false
>   power_down: true
>   power_down_on_quit: false
>   player_difficulty: true
>   3d_doors: true
>   village_travel: false
>   perception_filter: true
>   repair: true
> growth:
>   gravity_max_distance: 15
>   gravity_max_velocity: 5
>   return_room_seed: true
>   rooms_require_blocks: false
>   rooms_condenser_percent: 100
>   room_speed: 4
>   ars_limit: 1
> arch:
>   enabled: true
>   min_time: 20
>   switch_inventory: true
>   clear_inv_on_death: false
> siege:
>   enabled: true
>   breeding: 0
>   growth: 0
>   butcher: false
>   creeper: false
>   healing: false
>   texture: false
> junk:
>   enabled: true
>   return: -1
>   particles: true
> abandon:
>   enabled: false
>   reduce_count: true
> archive:
>   enabled: true
>   limit: 3
> handles:
>   prefix: Hey Handles
>   reminders:
>     enabled: true
>     schedule: 1200
> rechargers: {}
> conversions:
>   ars_materials: true
>   condenser_materials: true
>   player_prefs_materials: true
>   block_materials: true
>   custom_preset: true
>   constructs: true
>   lowercase_world_names: true
>

**Comment by pdglobal** [comment] 2020-02-11 20:55
https://drive.google.com/open?id=1xJSb57oUoxHRlSm64pnct2ryF3CniWjB

**Comment by pdglobal** [comment] 2020-02-11 20:59
Also here is a snapshot of my current most up to date plugins folder.

https://drive.google.com/open?id=1xJSb57oUoxHRlSm64pnct2ryF3CniWjB

**Comment by eccentricdevotion** [comment] 2020-02-11 21:06
Same link...

**Comment by eccentricdevotion** [comment] 2020-02-11 21:18
My region file, fresh server install:

```
regions:
    tardis_thenosefairy:
        min: {x: 0, y: 0, z: 0}
        max: {x: 1023, y: 256, z: 1023}
        members: {}
        flags: {entry: deny, exit: deny, lava-fire: deny, use: allow, lighter: deny,
            lava-flow: deny, fire-spread: deny}
        owners:
            players: [thenosefairy]
        type: cuboid
        priority: 0
    tardis_eccentric_nz:
        min: {x: 0, y: 0, z: 1024}
        max: {x: 1023, y: 256, z: 2047}
        members: {}
        flags: {entry: deny, exit: deny, lava-fire: deny, use: allow, lighter: deny,
            lava-flow: deny, fire-spread: deny}
        owners:
            players: [eccentric_nz]
        type: cuboid
        priority: 0
```

**Comment by pdglobal** [comment] 2020-02-11 21:32
Sorry, here's the proper link to my plugins folder https://drive.google.com/open?id=1Lle4cyb--u9mPWroPiZUMzWqEvyIfItd

**Comment by eccentricdevotion** [comment] 2020-02-11 21:40
I can't even get the server to start up with those plugins, too many errors...

**Comment by pdglobal** [comment] 2020-02-11 21:55
You're using paper build 102?

**Comment by pdglobal** [comment] 2020-02-11 21:59
IDK if this matters or not, but I'm using Java SE 13.0.2 JDK to to run the server.

**Comment by eccentricdevotion** [comment] 2020-02-11 22:01
Yup.
Residence shuts down the server.
`Your server version is not compatible with this plugins version! Plugin will be disabled: v1_15 and server will shutdown`

**Comment by eccentricdevotion** [comment] 2020-02-11 22:06
I wouldn't recommend using Java 13 - Minecraft itself is developed and shipped with 8...

**Comment by eccentricdevotion** [comment] 2020-02-11 22:11
```
[11:08:27 INFO]: [TARDIS] Enabling TARDIS v4.3-b1993
[11:08:27 INFO]: [TARDIS] This plugin requires LibsDisguises to be v9.9.0 or higher, disabling...
[11:08:27 INFO]: [TARDIS] Disabling TARDIS v4.3-b1993
```

**Comment by pdglobal** [comment] 2020-02-11 22:21
I'm so sorry, that's 100% my fault, I sent you the wrong backup. 

here's the proper one: https://drive.google.com/open?id=1Lle4cyb--u9mPWroPiZUMzWqEvyIfItd
(I know it;s the same link, but the proper file is there now)

Also I downgraded to jre 8, now I get the error in the following log when trying to enter my TARDIS after building it:
https://pastebin.com/5b2MUhDe

Now I'm not sure what's wrong other than when I try to open the door I get the errors at the bottom of that log file.

**Comment by eccentricdevotion** [comment] 2020-02-11 22:24
Yep, currently tracking that error here: https://dev.bukkit.org/projects/tardis/issues/1683 and here: https://dev.bukkit.org/projects/tardis/issues/1595
You should be able to do a /tadmin purge [player] and create the TARDIS again - will be fixed in next build.

**Comment by pdglobal** [comment] 2020-02-11 22:30
Okay, I got rid of the already reported error, under java 8, managed to get 2 tardises created.

I'm still experiencing this issue.

The two worldguard regions are overlapping and the door from the first tardis leads into the second tardis, and the doors inside both TARDISses exit to the outside door of the second TARDIS.

Could it be my worldguard or worldedit plugin versions?

**Comment by eccentricdevotion** [comment] 2020-02-11 22:51
Still can't reproduce using your plugins (and java 13 just in case).

**Comment by pdglobal** [comment] 2020-02-11 23:51
If you used the exact same plugin config as me, any idea what could be actually causing this behavior? I would have assumed the problem was in the plugins folder

**Comment by pdglobal** [comment] 2020-02-12 00:55
removed all plguisn except tardis world guard, worldedit, residence, and group manager, and I tried without each of those 1 by 1 so I know none of them are causing it, now when I try to enter a TARDIS my server crashed and dumps the following:

https://pastebin.com/3KmBdrv9

**Comment by pdglobal** [comment] 2020-02-12 00:59
Got past that error when the server booted back up, went inside my tardis(the 1st one created) and found myself inside my friend's TARDIS, (second TARDIS created)

I have absolutely no idea why it could be behaving like this. Even with just TARDIS by itself, the error occurs still.

**Comment by pdglobal** [comment] 2020-02-12 01:16
Okay, more accurately I see now that every new TARDIS created actually send people to the very 1st console, and that the out door inside the console is always linked to the most recently created TARDIS exterior.... strange..... very strange. I've litterally delete everything from my server folder except the bare minimum for TARDIS to function, and I still get this behavior.

**Comment by eccentricdevotion** [comment] 2020-02-12 01:59
You'd have to start afresh with no TARDISes to test, as existing TARDISes are screwed up.
Delete the TARDIS_TimeVortex world and start with just TARDIS & TARDISChunkGenerator & WorldEdit/WorldGuard.
Add plugins one by one to see if one of them might be the culprit.
If I can't reproduce it, there's not a lot I can do from my end.

**Comment by pdglobal** [comment] 2020-02-12 02:25
That's what I did and I get the same results? Is there anything I can do on my end to provide more useful information?

**Comment by PrincessRTFM** [comment] 2020-02-12 02:26
Try deleting the TARDIS config folder too? Maybe your configs are messed up somehow.

**Comment by eccentricdevotion** [comment] 2020-02-12 03:00
Server in online mode? Shouldn't make a difference, but trying to eliminate possibilities.
Server operating system?
Are TARDISes created simultaneously by different players or is there a period of time (however short) between creation?

**Comment by eccentricdevotion** [comment] 2020-02-12 03:22
If you view the TARDIS_TimeVortex world in something like  Minutor are the TARDIS created in their own plot?

**Comment by eccentricdevotion** [comment] 2020-02-12 03:22
Attach TARDIS database from a glitched install.

**Comment by eccentricdevotion** [comment] 2020-02-12 05:01
OK, I think it might be your version of WorldGuard - I noticed an error with a reduced amount of plugins...
Try this one:  https://builds.enginehub.org/job/worldguard/13665
With WorldEdit: https://builds.enginehub.org/job/worldedit/13711

**Comment by pdglobal** [comment] 2020-02-12 22:01
I am using windows server 2019 standard, running on online mode, and the error happens both when created at the same time, and with one created a short period after another.

I tried using those versions of WE and WG with no avail.

Attached is the database file:
https://drive.google.com/open?id=1GgwIIFpCpVm9YwWcJW1YL3p914ERYrB6

**Comment by pdglobal** [comment] 2020-02-12 22:15
My environment is System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07) Host:  Windows Server 2019 10.0 (amd64)

And it;s worth noting I tried completely deleting the TARDIS config folder and letting it regenerate with all default settings, more than once.

**Comment by pdglobal** [comment] 2020-02-12 22:55
Also I tried to view the timevortex in minutor and mcedit, and both crashed when opening my world folder, I've never used either one before so idk if it's user error or because of some lack of support for 1.15.2 server world I'm trying to load, but I did go outside the TARDIS console and check for any other consoles in N, E, S, W and didn't see any. I'm assuming it's building the new TARDIS over top of the old TARDIS, because the old TARDIS takes me to the newest console created, and then once I'm inside the door inside takes me to the outside of the most recently created TARDIS.

**Comment by pdglobal** [comment] 2020-02-12 23:30
Also might be useful to note that everything worked fine before upgrading to support 1.15.2

**Comment by eccentricdevotion** [comment] 2020-02-13 00:02
So the problem is that the plugin is not getting the next free TIPS (**T**ARDIS **I**nterior **P**ositioning  **S**lot). In the database, both TARDISes have the same slot number (`-1`) _which isn't even a valid TIPS slot._
At this stage I have no idea why (and the code for determining the slot hasn't changed between 1.14 and 1.15 or in fact significantly since 2014...

**Comment by eccentricdevotion** [comment] 2020-02-13 00:16
Can you try build 1999 on a fresh install - http://tardisjenkins.duckdns.org:8080/job/TARDIS/

- Start the server to generate default files
- Run the `/tardisadmin debug true` command
- Stop server
- Start the server
- Create 2 TARDISes
- Post server log

**Comment by pdglobal** [comment] 2020-02-13 01:07
Wasn't able to get past step 2

When I load my server with just the TARDIS plugin 1999 and tardis chunk gen I get the following error:
https://pastebin.com/HWr9qt3r

**Comment by eccentricdevotion** [comment] 2020-02-13 01:59
Oops, my bad, new build running now

**Comment by pdglobal** [comment] 2020-02-13 03:27
new build failing with the following errors:
https://pastebin.com/sGu26vC0

(build 2000)

**Comment by eccentricdevotion** [comment] 2020-02-13 03:30
Darn it missed one, either use build 2001, _or_ add the latest TARDISWeepingAngels plugin in there too

**Comment by pdglobal** [comment] 2020-02-13 05:02
Okay build 2001 doesnt act this way, its working perfectly!

**Comment by eccentricdevotion** [comment] 2020-02-13 05:03
Interesting, as I have actually changed any code, just added debug statements...

**Comment by pdglobal** [comment] 2020-02-13 05:43
IDK, but it's working like it should now, that was really weird, what's weirder is that I have no idea why it was happening and you seem to have no idea what was causing it either xD

**Closed** 2020-02-15 06:26 UTC
Labels: bug, cannot reproduce
