### ISSUE TITLE
TARDIS item dupe bug

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#695] opened 2023-01-30 15:23 UTC
### Describe the bug

https://www.xbox.com/play/media/JRVDB4SU7R

### To Reproduce

It's all in the video but seems to always occur unless I change dimension before entering 

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

In video

**Comment by eccentricdevotion** [comment] 2023-01-30 19:43
Unlikely to be TARDIS, there is no inventory code related to entering and exiting the TARDIS that would cause this.
I cannot reproduce using my server.
Possible plugin conflict? Can you reproduce with just TARDIS & TARDISChunkGenerator?

**Comment by Batman2741** [comment] 2023-01-31 14:57
> Unlikely to be TARDIS, there is no inventory code related to entering and exiting the TARDIS that would cause this.
> I cannot reproduce using my server.
> Possible plugin conflict? Can you reproduce with just TARDIS & TARDISChunkGenerator?

It is possible to be multiverse inventory doing this but it only happens for TARDIS world's and only when each TARDIS has its own world

**Comment by eccentricdevotion** [comment] 2023-01-31 19:40
Okay, will need to see your Multiverse-Core and Multiverse-Inventories configs.

**Comment by eccentricdevotion** [comment] 2023-02-01 00:19
I still can't reproduce with MVI installed...

**Comment by eccentricdevotion** [comment] 2023-02-01 21:48
I noticed some other issues when Multiverse is installed which should be fixed in build 2513, can you update and see if the dupe bug still happens for you?

**Comment by Batman2741** [comment] 2023-02-11 23:30
> I noticed some other issues when Multiverse is installed which should be fixed in build 2513, can you update and see if the dupe bug still happens for you?

Still happens

**Comment by Batman2741** [comment] 2023-02-11 23:36
> Okay, will need to see your Multiverse-Core and Multiverse-Inventories configs.

Here is the config for core I'll send inventory config in a sec![image-3.png](https://user-images.githubusercontent.com/104590478/218285556-e170e92c-0371-45f4-a5b9-70fc5a202575.png)

**Comment by Batman2741** [comment] 2023-02-11 23:43
> > Okay, will need to see your Multiverse-Core and Multiverse-Inventories configs.
> 
> Here is the config for core I'll send inventory config in a sec![image-3.png](https://user-images.githubusercontent.com/104590478/218285556-e170e92c-0371-45f4-a5b9-70fc5a202575.png)
> 
> 

![image-4.png](https://user-images.githubusercontent.com/104590478/218285708-ffc55cdc-b6c7-4f39-8829-c0fabe1057a0.png)

**Comment by eccentricdevotion** [comment] 2023-02-25 09:02
All the configs

**Closed** 2023-12-04 22:53 UTC
Labels: cannot reproduce, unconfirmed bug
