### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by InvictusAeternam** [eccentricdevotion/TARDIS#345] opened 2020-08-19 17:30 UTC
Not entirely sure why but my server (which only ever hosts myself and my girlfriend) seems to crash whenever one of us tries to travel anywhere in the TARDIS when we are both logged on. I have devoted a decent amount of RAM (12GB) to the server and didn't experience this back when I used to host servers with the TARDIS plugin on older versions. I have attached the full crash report, any ideas on what might have gone wrong are greatly appreciated. NOTE: I do use some other plugins but have no idea why they would cause me to crash when piloting the TARDIS
[crash-2020-08-18_22.31.07-server.txt](https://github.com/eccentricdevotion/TARDIS/files/5098215/crash-2020-08-18_22.31.07-server.txt)
EDIT: Having looked at other bug reports I realised I may have omitted some important information. I am running the latest version of Spigot for 1.16.2 with Jenkins build #2186 of the TARDIS plugin

**Comment by eccentricdevotion** [comment] 2020-08-19 18:48
This is a Spigot bug, if you are getting it, then you **don't** have the latest Spigot build on your server. Use BuildTools to compile the latest Jar file, or if you don't know how to do that download it from the TARDIS Jenkins server here: http://tardisjenkins.duckdns.org:8080/job/BuildTools/
Duplicate of #335 #338

**Comment by InvictusAeternam** [comment] 2020-08-19 19:10
Ah, thank you - sorry, I'll check more thoroughly in future :)

**Closed** 2020-08-19 19:11 UTC
Labels: Spigot bug, duplicate, outdated Spigot / Paper
