### ISSUE TITLE
Tardis Seeds

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#317] opened 2020-07-31 04:25 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
tardis 4.4.5-b2175
tardis gen 4.4.5
MC 1.16.1

the seeds will not craft for some reason. i get the GUI on how to craft the seed but it will not spawn a seed

**Comment by Chew** [comment] 2020-07-31 05:22
1) Duplicate of #314.
2) Make sure you don't have anything in the middle column.
3) Make sure the 3rd column are valid blocks, any [listed here](https://eccentricdevotion.github.io/TARDIS/walls.html)

**Comment by Airomis** [comment] 2020-07-31 05:26
Yrah unfortunately I know, the center is empty and the far right is wool. I used redstone lapis and iron on the far left

**Comment by Airomis** [comment] 2020-07-31 05:26
and yes iron ingot and redstone touch

**Comment by Chew** [comment] 2020-07-31 05:27
It should be Iron block (for the TARDIS type)

**Comment by Airomis** [comment] 2020-07-31 05:29
sorry thats what i ment to type

**Comment by Chew** [comment] 2020-07-31 05:30
Left column should for example be
Top Row: Redstone Torch
Middle Row: Lapis Lazuli BLOCK
Bottom Row: ANy BLOCKS listed here
![image](https://user-images.githubusercontent.com/8278263/89003256-ed9af580-d2c4-11ea-8b55-d47ef6705732.png)

**Comment by Chew** [comment] 2020-07-31 05:30
Also ensure you have proper permissions if you are using a permission plugin, these are [here](https://eccentricdevotion.github.io/TARDIS/permissions-table.html)

**Comment by Airomis** [comment] 2020-07-31 05:33
I have OP and tardis.*

**Comment by Chew** [comment] 2020-07-31 05:33
Not entirely sure tardis.* is supported, you may need `tardis.use` and `tardis.admin`

**Comment by Airomis** [comment] 2020-07-31 05:34
Ot was in the list unless its not supposed anymore

**Comment by eccentricdevotion** [comment] 2020-07-31 07:59
`tardis.*` has _never_ been supported

**Comment by Airomis** [comment] 2020-07-31 15:34
i have tardis.use tardis.admin it must have been dumb luck in the past that i had other settings right and it worked i looked at old perms and it was there.

**Comment by Airomis** [comment] 2020-07-31 15:39
![image](https://user-images.githubusercontent.com/10307394/89051575-7a27d100-d322-11ea-8139-ddfb6a244483.png)

![image](https://user-images.githubusercontent.com/10307394/89051609-8744c000-d322-11ea-86b2-dcd50ae618eb.png)

**Comment by Chew** [comment] 2020-07-31 19:26
Show a screenshot of your crafting grid too

**Comment by Airomis** [comment] 2020-07-31 20:19
![image](https://user-images.githubusercontent.com/10307394/89074053-a145c900-d349-11ea-8b2b-cb22ab78ebbf.png)

**Comment by Airomis** [comment] 2020-07-31 20:20
redstone , lapis 2 wools and an iron block

**Comment by eccentricdevotion** [comment] 2020-08-01 03:29
It seems as though you have permission, and the crafting is ok, so it must be something else.

1. Is the plugin actually enabled? Include the server startup log as requested in the issue template
2. Is a dependent plugin out of date? Include the output of `/tardis version` as requested in the issue template
3. Is there a conflicting plugin? Check for plugin that may alter server recipes.
4. Do other TARDIS features work? Have you tried giving yourself a seed block with `/tgive airomis seed budget`, can you access the tardis help commands `/tardis help` etc

**Comment by Chew** [comment] 2020-08-01 03:44
1 and 2 were answered here
![image](https://user-images.githubusercontent.com/8278263/89093374-5cd52000-d37f-11ea-9515-b74eeb5c2965.png)

**Comment by eccentricdevotion** [comment] 2020-08-01 03:59
Yeah, I saw that after I commented, though I don't think that fully rules out 1

Don't think build numbers are actually being set, as the plugin is up to date...

**Comment by Airomis** [comment] 2020-08-01 04:00
[2020-07-30-10.log.gz](https://github.com/eccentricdevotion/TARDIS/files/5009811/2020-07-30-10.log.gz)

**Comment by eccentricdevotion** [comment] 2020-08-01 04:07
3 Check for conflicting plugins. Can you craft if only TARDIS & TARDISChunkGenerator are enabled?

**Comment by Airomis** [comment] 2020-08-01 04:07
i did the /tgive airomis seed budget and it worked

**Comment by Airomis** [comment] 2020-08-01 05:00
so it looks like if the world boarder.jar is in the plugin folder and gets disabled it will not let you craft the seed block

**Comment by eccentricdevotion** [comment] 2020-08-01 06:17
You don't need WorldBorder for TARDIS anymore, but interesting... I'll see if I can reproduce.

**Comment by eccentricdevotion** [comment] 2020-08-05 02:51
Can't seem to reproduce on my test server - there is an updated version of WorldBorder if you want to use it: https://www.spigotmc.org/resources/worldborder-1-15.80466/
Build 2180 makes sure the `switch_resource_packs` boolean value is set correctly when using the `/tadmin` command to set it.

**Closed by eccentricdevotion** 2020-08-05 02:51 UTC
Labels: cannot reproduce, plugin conflict
