### ISSUE TITLE
Cant craft tardis seed

### ISSUE THREAD

**Issue by 56Kirito56** [eccentricdevotion/TARDIS#314] opened 2020-07-21 20:42 UTC
**Describe the bug** im running the tardis plugin on 1.16 my server is on 1.16.1 the issue is you can not craft a tardis seed blocks there is no command errors

**To Reproduce**
Steps to reproduce the behaviour:
1. Install '...'
2. Start '...'
3. Type '...'

**Screenshots**

**Log files**
If applicable, paste your server log (_showing the whole server startup to when the error occurs_) on a website like pastebin.com, and post a link here.

**`/tardis version` output**
Please include an output of your `/tardis version`.

**Comment by eccentricdevotion** [comment] 2020-07-21 20:56
Duplicate of #313

**Closed by eccentricdevotion** 2020-07-21 20:56 UTC
Labels: duplicate

**Comment by 56Kirito56** [comment] 2020-07-23 01:23
Tardis says to update repeaters when desk top is changed 


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 4:56 PM, Eccentric Devotion <notifications@github.com> wrote:




Closed #314.
