### ISSUE TITLE
No way to disable HADS?

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#260] opened 2020-04-20 01:15 UTC
**Describe the bug**
Bell is ringing, the redstone lights all have that siege mode versions of themselves up, the tardis will travel wherever and otherwise operates normally but HADS has clearly been triggered (displacement not dispersal... I tried the reassemble command anyway which didn't help).

**To Reproduce**
Steps to reproduce the behaviour:
1. No idea what the player did to trigger the incident but this seems to be a normal displacement incident... there's just no way to end it.

**Comment by eccentricdevotion** [comment] 2020-04-20 01:31
What TARDIS build?
There were HADS related updates yesterday

**Comment by mrcoffee1026** [comment] 2020-04-20 01:32
2074

**Comment by Chew** [comment] 2020-04-20 03:29
Make sure you have [TARDIS Build 2078](http://tardisjenkins.duckdns.org:8080/job/TARDIS/lastSuccessfulBuild) AND [TARDISChunkGenerator build 92](http://tardisjenkins.duckdns.org:8080/view/TARDIS/job/TARDISChunkGenerator/lastSuccessfulBuild).

**Comment by mrcoffee1026** [comment] 2020-04-20 14:12
Ok we'll give these a try.  Also can you make it so that sfx_volume can be adjusted without restarting the server?  Changing the value and doing then even doing a tardis reload does nothing, but restarting  after changing the value will.  Thank you!

**Comment by mrcoffee1026** [comment] 2020-04-20 14:37
We can't open the tardis doors with their keys in this build... shift+clicking still works to enter the tardis without opening the door.

**Comment by Chew** [comment] 2020-04-20 17:13
> even doing a tardis reload does nothing

Doing `/tardisadmin reload` right? `/tardis reload` isn't a thing.

> We can't open the tardis doors with their keys in this build

What does the error in chat say?

**Comment by mrcoffee1026** [comment] 2020-04-20 17:48
we don't get an error, the door just won't open.  and yes i mean the /tardisadmin reload when attempting to get the sound change to "take".

**Comment by eccentricdevotion** [comment] 2020-04-20 19:28
> not sure if it matters but seems like at least my tardis and possibly others went hidden after the last restart

There no code in the plugin that would cause this

**Comment by mrcoffee1026** [comment] 2020-04-20 19:30
may just be some weird unrelated thing then.

**Comment by eccentricdevotion** [comment] 2020-04-21 00:09
Must be, as I can't reproduce you r door problem either

**Comment by mrcoffee1026** [comment] 2020-04-26 02:42
It hasn't happened to anyone else since this later build so unless it comes up again I'll assume whatever you've changed has resolved the situation.

**Comment by PrincessRTFM** [comment] 2020-04-26 03:49
If you feel the issue has been resolved, please close this entry on the issue tracker

**Closed** 2020-04-26 06:29 UTC
Labels: bug
